version: 2

updates:
  - package-ecosystem: npm
    directory: /

    schedule:
      interval: weekly
      day: monday
      time: "19:00"
      timezone: "Europe/Tallinn"

    groups:
      all-updates:
        applies-to: version-updates

        patterns:
          - "*"
