name: Build and Deploy

permissions:
  contents: read
  pull-requests: write

# Deploy to staging on PRs, to production on pushes to default branch
on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  deploy:
    uses: Perdolique/automations/.github/workflows/deploy.yml@v3.3.0
    with:
      working-directory: '.'
      artifact-path: 'dist'
      artifact-name: 'blog-artifact'
      build-command: 'build'
      test-typecheck-command: 'test:typecheck'
      deploy-to-staging-command: 'deploy:preview'
      deploy-to-production-command: 'deploy'
    secrets:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
